services:
  backend:
    image: nethra0810/femcare-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - CLIENT_URL=http://frontend:5173

  frontend:
    image: nethra0810/femcare-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo