- name: Deploy FemCare App
  hosts: localhost
  connection: local

  tasks:
    - name: Force stop old containers
      command: docker-compose down --remove-orphans

    - name: Recreate containers
      command: docker-compose up -d --build --force-recreate