- name: Deploy FemCare App
  hosts: localhost
  connection: local

  tasks:
    - name: Stop old containers
      command: docker-compose down

    - name: Run Docker Compose
      command: docker-compose up -d --build